### ISSUE TITLE
Create implementation example

### ISSUE THREAD

**Issue by birgersp** [chdh/commons-math-interpolation#3]
Hi,

Can you please provide some implementation examples? How can I use this library in my own application?

**Comment by chdh** [comment]
I have added a [simple example](https://github.com/chdh/commons-math-interpolation/tree/master/examples). But to really understand it, you have to look at the [source code of the package](https://github.com/chdh/commons-math-interpolation/tree/master/src). The documentation is in the comments in the source code.
